const {test}=require('node:test'),assert=require('node:assert/strict');
const {run}=require('../scripts/migrate-auth.cjs');
function fixture(){
 const root={users:{admin:{id:'admin',kullaniciAdi:'admin',sifre:'OLD_SECRET',aktif:true},a:{id:'a',kullaniciAdi:'veli',adSoyad:'VELİ',sifre:'OLD_SECRET',seasonStates:{s:true},aktif:true}},predictions:{keep:{playerId:'a',matchId:'phone-id',sheetMatchId:'shared-id',homePred:2}},settings:{dataManagementTrash:{old:{data:{password:'OLD_SECRET'}}}}};
 const writes=[],created=[],claims=[];
 const db={ref(){return {get:async()=>({val:()=>structuredClone(root)}),update:async values=>{writes.push(values);for(const [k,v]of Object.entries(values)){if(k==='serverPrivate/authMigration'){root.serverPrivate={authMigration:v};}else root[k]=v;}}};}};
 const auth={getUserByEmail:async()=>({uid:'google-uid',emailVerified:true,providerData:[{providerId:'google.com'}]}),getUser:async uid=>{if(uid==='google-uid')return {uid};throw Object.assign(new Error(),{code:'auth/user-not-found'});},createUser:async value=>created.push(value),setCustomUserClaims:async(...v)=>claims.push(v)};
 return {root,writes,created,claims,options:{env:{ADMIN_EMAIL:'mustafayargin@gmail.com'},servicesFactory:()=>({auth,db}),log:()=>{}}};
}
test('migration dry-run makes no Auth or Database writes',async()=>{const f=fixture();await run({...f.options,args:['--admin-player-id','admin']});assert.equal(f.writes.length,0);assert.equal(f.created.length,0);assert.equal(f.claims.length,0);});
test('migration preserves prediction identities, removes archived plaintext and binds Google admin',async()=>{const f=fixture(),before=structuredClone(f.root.predictions);await run({...f.options,args:['--admin-player-id','admin','--apply','--backup-confirmed']});assert.deepEqual(f.root.predictions,before);assert.equal(f.root.users.a.id,'a');assert.equal(f.root.users.admin.authUid,'google-uid');assert.equal(f.root.authAccess['google-uid'].role,'admin');assert.equal(JSON.stringify(f.root).includes('OLD_SECRET'),false);assert.equal(f.created.length,1);assert.notEqual(f.created[0].password,'OLD_SECRET');assert.equal(f.root.authAccess[f.created[0].uid].mustChangePassword,true);await assert.rejects(run({...f.options,args:['--admin-player-id','admin','--apply','--backup-confirmed']}));assert.equal(f.created.length,1);});
test('apply needs backup acknowledgement; ambiguous login names stop migration',async()=>{const f=fixture();await assert.rejects(run({...f.options,args:['--admin-player-id','admin','--apply']}));f.root.users.b={id:'b',kullaniciAdi:'VELİ'};await assert.rejects(run({...f.options,args:['--admin-player-id','admin']}));assert.equal(f.writes.length,0);});
