const {test}=require('node:test'),assert=require('node:assert/strict');
const p=require('../server/policy.cjs'),{identify,execute}=require('../server/service.cjs');
function fixture(){
 const root={users:{a:{id:'a',authUid:'uid-a',aktif:true,rol:'user',kullaniciAdi:'veli',adSoyad:'VELİ'},b:{id:'b',authUid:'uid-b',aktif:true,rol:'user'},admin:{id:'admin',authUid:'uid-admin',aktif:true,rol:'admin'}},authAccess:{'uid-a':{playerId:'a',active:true,role:'user'},'uid-admin':{playerId:'admin',active:true,role:'admin'}},matches:{remote:{id:'remote',date:new Date(Date.now()+24*3600e3).toISOString(),seasonId:'s',weekId:'w',weekNo:1,homeTeam:'A',awayTeam:'B'}},settings:{weeksMeta:[{id:'w',seasonId:'s',number:1,status:'yayinlandi'}]},predictions:{}};
 let counter=0;const writes=[],calls=[];
 const db={ref(path=''){const parts=path.split('/').filter(Boolean),get=()=>parts.reduce((v,k)=>v?.[k],root)??null;
 function set(value){let cur=root;for(const part of parts.slice(0,-1))cur=cur[part]??={};if(value===null)delete cur[parts.at(-1)];else cur[parts.at(-1)]=structuredClone(value);writes.push(path);}
 return {get:async()=>({val:()=>get()}),set:async v=>set(v),update:async values=>{for(const [k,v]of Object.entries(values))await db.ref([path,k].filter(Boolean).join('/')).set(v);},push:()=>({key:`log${++counter}`})};}};
 const auth={verifyIdToken:async(token,revoked)=>{calls.push(['verify',revoked]);if(token==='bad')throw Error();return {uid:token,auth_time:Math.floor(Date.now()/1000),...(token==='uid-admin'?{admin:true}:{})};},updateUser:async(uid,v)=>calls.push(['update',uid,v]),revokeRefreshTokens:async uid=>calls.push(['revoke',uid]),createUser:async v=>calls.push(['create',v]),deleteUser:async uid=>calls.push(['delete',uid])};
 return {root,db,auth,calls,writes,actor:{uid:'uid-a',playerId:'a',access:root.authAccess['uid-a'],profile:root.users.a,admin:false,authTime:Date.now()/1000},admin:{uid:'uid-admin',playerId:'admin',access:root.authAccess['uid-admin'],profile:root.users.admin,admin:true}};
}
test('invalid/unmapped tokens and disabled profiles denied; revoked tokens checked',async()=>{const f=fixture();await assert.rejects(identify(f.auth,f.db,'bad'));await assert.rejects(identify(f.auth,f.db,'unknown'));assert.equal((await identify(f.auth,f.db,'uid-a')).admin,false);assert.ok(f.calls.every(c=>c[1]===true));f.root.users.a.aktif=false;await assert.rejects(identify(f.auth,f.db,'uid-a'));});
test('forged profile role and panelAdmin cannot grant authority',async()=>{const f=fixture();f.root.users.a.rol='admin';f.root.users.a.panelAdmin=true;assert.equal((await identify(f.auth,f.db,'uid-a')).admin,false);f.root.authAccess['uid-a'].revokeTime=Math.floor(Date.now()/1000);await assert.rejects(identify(f.auth,f.db,'uid-a'));});
test('another player cannot be written, and no write occurs',async()=>{const f=fixture();await assert.rejects(execute(f,f.actor,'savePrediction',{playerId:'b',sheetMatchId:'remote',homePred:1,awayPred:0}),e=>e.status===403);assert.equal(f.writes.length,0);});
test('week lock, manual override, finished match and temporary password enforced',()=>{const f=fixture(),m=f.root.matches.remote,w=f.root.settings.weeksMeta[0];m.date=new Date().toISOString();assert.throws(()=>p.assertPredictionAllowed(f.actor,'a',m,f.root.matches,f.root.settings));w.predictionManualOpen=true;p.assertPredictionAllowed(f.actor,'a',m,f.root.matches,f.root.settings);w.predictionManualLocked=true;assert.throws(()=>p.assertPredictionAllowed(f.actor,'a',m,f.root.matches,f.root.settings));w.predictionManualLocked=false;m.played=true;assert.throws(()=>p.assertPredictionAllowed(f.actor,'a',m,f.root.matches,f.root.settings));m.played=false;f.actor.access.mustChangePassword=true;assert.throws(()=>p.assertPredictionAllowed(f.actor,'a',m,f.root.matches,f.root.settings));});
test('cross-device save preserves old identity; actor and scores are server controlled',async()=>{const f=fixture();f.root.predictions.old={id:'old',playerId:'a',matchId:'other-device',sheetMatchId:'remote'};const r=await execute(f,f.actor,'savePrediction',{playerId:'a',matchId:'this-device',sheetMatchId:'remote',homePred:2,awayPred:1,actorRole:'admin',points:999});assert.equal(r.id,'old');assert.equal(f.root.predictions.old.matchId,'other-device');assert.equal(f.root.predictions.old.actorRole,'user');assert.equal(f.root.predictions.old.points,undefined);});
test('invalid scores and missing match rejected without writes',async()=>{const f=fixture();for(const homePred of [-1,100,1.2,'',null])await assert.rejects(execute(f,f.actor,'savePrediction',{playerId:'a',sheetMatchId:'remote',homePred,awayPred:1}));await assert.rejects(execute(f,f.actor,'savePrediction',{playerId:'a',matchId:'missing',homePred:1,awayPred:1}));assert.equal(f.writes.length,0);});
test('others predictions hidden until reveal; own visible',async()=>{const f=fixture();f.root.predictions={own:{playerId:'a',sheetMatchId:'remote'},other:{playerId:'b',sheetMatchId:'remote'}};assert.deepEqual((await execute(f,f.actor,'getPredictions')).predictions.map(v=>v.id),['own']);f.root.settings.weeksMeta[0].predictionManualLocked=true;assert.equal((await execute(f,f.actor,'getPredictions')).predictions.length,2);});
test('reset preserves predictions and account UID; no password stored',async()=>{const f=fixture();f.root.predictions.keep={playerId:'a',homePred:2};const before=structuredClone(f.root.predictions);const r=await execute(f,f.admin,'updateUser',{id:'a',resetPassword:true});assert.ok(r.temporaryPassword.length>=12);assert.deepEqual(f.root.predictions,before);assert.equal(f.root.users.a.authUid,'uid-a');assert.equal(f.root.users.a.sifre,undefined);assert.equal(f.root.authAccess['uid-a'].mustChangePassword,true);assert.ok(f.calls.some(c=>c[0]==='revoke'));});
test('ordinary account cannot manage users; Google admin is protected',async()=>{const f=fixture();await assert.rejects(execute(f,f.actor,'addUser',{adSoyad:'NEW'}));await assert.rejects(execute(f,f.actor,'updateUser',{id:'b',resetPassword:true}));await assert.rejects(execute(f,f.admin,'updateUser',{id:'admin',aktif:false}));await assert.rejects(execute(f,f.admin,'updateUser',{id:'a',panelAdmin:true}));assert.equal(f.writes.length,0);});
test('password change requires recent login and revokes old sessions',async()=>{const f=fixture();f.actor.authTime-=600;await assert.rejects(execute(f,f.actor,'changePassword',{password:'a-long-password-42'}));f.actor.authTime=Date.now()/1000;await execute(f,f.actor,'changePassword',{password:'a-long-password-42'});assert.ok(f.calls.some(c=>c[0]==='revoke'));assert.equal(f.root.authAccess['uid-a'].mustChangePassword,false);});
test('nested backups and archives stripped of passwords',()=>{assert.equal(JSON.stringify(p.clean({a:{sifre:'secret',password:'secret'},trash:[{value:{adminPassword:'secret'}}]})).includes('secret'),false);});
test('Turkish normalization stable',()=>{assert.equal(p.accountEmail(' İBRAHİM '),p.accountEmail('ibrahim'));assert.equal(p.accountEmail('ÖZKAN'),p.accountEmail('ozkan'));});
test('season exclusion cannot be bypassed through direct API',async()=>{const f=fixture();f.actor.profile.seasonStates={s:false};await assert.rejects(execute(f,f.actor,'savePrediction',{playerId:'a',sheetMatchId:'remote',homePred:1,awayPred:1}),e=>e.status===403);assert.equal(f.writes.length,0);});
test('temporary password grants session and password change only',async()=>{const f=fixture();f.actor.access.mustChangePassword=true;await execute(f,f.actor,'session');for(const action of ['getPredictions','getSettings','updateUser'])await assert.rejects(execute(f,f.actor,action,{id:'a',supportedTeam:'A'}),e=>e.status===403);assert.equal(f.writes.length,0);});
test('own team editable but ownership, role and season changes denied',async()=>{const f=fixture();await execute(f,f.actor,'updateUser',{id:'a',supportedTeam:'Galatasaray'});assert.equal(f.root.users.a.supportedTeam,'Galatasaray');for(const payload of [{id:'b',supportedTeam:'A'},{id:'a',rol:'admin'},{id:'a',seasonStates:{s:true}}])await assert.rejects(execute(f,f.actor,'updateUser',payload),e=>e.status===403);});
test('forced logout revokes server access without deleting predictions',async()=>{const f=fixture();f.root.predictions.keep={playerId:'a'};await execute(f,f.admin,'forceLogout',{id:'a'});await assert.rejects(identify(f.auth,f.db,'uid-a'),e=>e.status===401);assert.ok(f.root.predictions.keep);});
test('legacy matches without season/week IDs use authoritative registries',async()=>{const f=fixture();delete f.root.matches.remote.seasonId;delete f.root.matches.remote.weekId;f.root.matches.remote.sezon='2026-2027';f.root.settings.seasonsMeta=[{id:'s',name:'2026-2027'}];const r=await execute(f,f.actor,'savePrediction',{playerId:'a',sheetMatchId:'remote',homePred:1,awayPred:0});assert.equal(f.root.predictions[r.id].seasonId,'s');assert.equal(f.root.predictions[r.id].weekId,'w');f.actor.profile.seasonStates={s:false};await assert.rejects(execute(f,f.actor,'savePrediction',{playerId:'a',sheetMatchId:'remote',homePred:1,awayPred:1}));});
test('unrelated legacy match cannot reveal a future week',()=>{const f=fixture();f.root.settings.seasonsMeta=[{id:'s',name:'2026-2027'}];delete f.root.matches.remote.weekId;delete f.root.matches.remote.seasonId;f.root.matches.remote.sezon='2026-2027';f.root.matches.unrelated={id:'unrelated',sezon:'2025-2026',haftaNo:1,date:'2025-10-01T12:00',played:true};assert.equal(p.canReveal(f.actor,{playerId:'b',sheetMatchId:'remote'},f.root.matches,f.root.settings),false);});
test('notification device registration binds server identity and migrates legacy token',async()=>{const f=fixture(),token='dummy-notification-token-for-tests';f.root.fcmTokens={old:{token,userId:'b'}};await execute(f,f.actor,'registerFcmToken',{token,deviceId:'phone',userId:'b',playerId:'b',role:'admin'});assert.equal(f.root.fcmTokens.old,undefined);const record=Object.values(f.root.fcmTokens)[0];assert.equal(record.playerId,'a');assert.equal(record.authUid,'uid-a');assert.equal(record.role,'user');});
